apiVersion: v2
name: inbox-zero
description: A Helm chart for running InboxJarvis on Kubernetes
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - inbox-zero
  - email
  - ai
  - nextjs
home: https://github.com/sv182124/InboxJarvis
sources:
  - https://github.com/sv182124/InboxJarvis
maintainers:
  - name: sv182124
